export const POWER_PRODUCTS = [
  {
    id: "kv-online-ups-system-31",
    slug: "online-ups-system-31",
    name: "Online UPS System (3-1 Phase)",
    category: "UPS",
    parentCategory: "Power Products",
    description: "Capacity: 10 KVA – 80 KVA. True Online Double Conversion 3-to-1 Phase UPS with DSP control, IGBT switching, and static bypass.",
    specifications: {
      "Phase": "3 Phase Input – 1 Phase Output",
      "Capacity Range": "10 KVA – 80 KVA",
      "Input Phase": "3 Phase",
      "Output Phase": "1 Phase",
      "Input Voltage": "415V AC ±15%",
      "Input Frequency": "50Hz ±6%",
      "DC Voltage": "360V / 384V DC",
      "Charging Time": "12 Hours (90% Capacity)",
      "Charger Type": "CVCC (Constant Current Constant Voltage)",
      "Inverter Technology": "DSP Based, IGBT Switching",
      "Output Voltage": "230V AC (Single Phase)",
      "Voltage Regulation": "±1%",
      "Output Frequency": "50Hz ±0.1Hz",
      "Waveform": "PWM Sine Wave",
      "Harmonic Distortion": "Less than 3% (Linear Load)",
      "Efficiency": "Up to 93%",
      "Inverter Efficiency": "Up to 90% (≤30 KVA) | Up to 93% (>30 KVA)",
      "Power Factor": "0.8",
      "Overload Capacity": "110% for 5 Minutes",
      "Crest Factor": "3:1",
      "Audible Noise": "Less than 65 dB @ 1 Meter",
      "Display Type": "Digital LCD Display",
      "Monitoring Parameters": "Input/Output Voltage, Output Current, Frequency, DC Voltage, Battery Status, Load %, Faults",
      "Indications & Alarms": "Mains ON (LED), Inverter ON (LED), Battery Low (LED & Alarm), Fault (LED & Alarm), Overload (LED & Alarm)",
      "Operating Temperature": "0°C to 40°C",
      "Humidity": "Maximum 95% (Non-Condensing)",
      "Protection": "Output Overload, Short Circuit, Output Under/Over Voltage, DC Under/Over Voltage, Mains Under/Over Voltage",
      "Optional Features": "SNMP Communication, Static Bypass"
    },
    image: "/products/online-ups-31.png",
    downloadUrl: "#",
    features: [
      "DSP Based Digital Control & IGBT Inverter Technology",
      "True Online Double Conversion Design with Pure Sine Wave",
      "Wide Input Voltage Range with Built-in Isolation Transformer",
      "Static Bypass & SNMP Communication Support",
      "Robust Design for Harsh Industrial Environments"
    ],
    applications: [
      "Computer & Data Centres",
      "Process Control Industries",
      "Broadcasting & Satellite Systems",
      "Safety Systems in Power Plants",
      "Healthcare & Laboratory Equipment",
      "Constant Voltage & Frequency Applications"
    ]
  },
  {
    id: "kv-online-ups-system-hf",
    slug: "online-ups-system-hf",
    name: "Online UPS System (High Frequency)",
    category: "UPS",
    parentCategory: "Power Products",
    description: "Capacity: 1 KVA / 2 KVA / 3 KVA. True Online High Frequency UPS with pure sine wave, ≥0.99 input power factor, and zero AC-to-DC transfer time.",
    specifications: {
      "Phase": "Single Phase",
      "Capacity Range": "1 KVA / 2 KVA / 3 KVA",
      "Power Rating": "800W / 1600W / 2400W",
      "UPS Type": "True Online High Frequency UPS",
      "Input Voltage Range": "110–300V AC (60% Load), 160–300V AC (100% Load)",
      "Input Frequency": "45–55 Hz / 55–65 Hz",
      "Input Power Factor": "≥0.99 @ Nominal Voltage",
      "Output Voltage": "208V / 220V / 230V / 240V AC",
      "Voltage Regulation": "±1%",
      "Output Frequency (Sync Mode)": "45–55 Hz / 56–64 Hz",
      "Output Frequency (Battery Mode)": "50Hz / 60Hz ±0.1Hz",
      "Current Crest Ratio": "3:1",
      "Harmonic Distortion": "≤3% (Linear Load), ≤6% (Non-Linear Load)",
      "Transfer Time (AC to DC)": "Zero",
      "Transfer Time (Inverter to Bypass)": "4ms (Typical)",
      "Output Waveform": "Pure Sine Wave",
      "Noise Level": "<55 dB @ 1 Meter",
      "Operating Humidity": "20–90% RH (Non-Condensing)",
      "Operating Temperature": "0°C to 40°C",
      "Efficiency (AC Mode)": "1 KVA: 88% | 2 KVA: 89% | 3 KVA: 90%",
      "Efficiency (Battery Mode)": "1 KVA: 83% | 2 KVA: 85% | 3 KVA: 86%",
      "Battery Type": "12V / 7Ah",
      "Internal Battery Qty": "1 KVA: 3 | 2 KVA: 6 | 3 KVA: 6 or 8",
      "Charging Current": "Internal: 1A | Long Backup: 6A",
      "Dimensions (D × W × H)": "1 KVA: 415 × 145 × 215 mm | 2 KVA: 475 × 192 × 340 mm | 3 KVA: 475 × 192 × 340 mm",
      "Weight (Net / Gross)": "1 KVA: 7.5 / 9 kg | 2 KVA: 14 / 16 kg | 3 KVA: 15 / 17 kg"
    },
    image: "/products/online-ups-hf.png",
    downloadUrl: "#",
    features: [
      "Compact Design for Easy Installation & Space Saving",
      "High Power Density & High Reliability",
      "Extended Battery Backup Capability",
      "LCD Display for Real-Time Monitoring",
      "Energy Efficient Operation with Pure Sine Wave Output",
      "Wide Input Voltage Range"
    ],
    applications: [
      "Computer & Data Centres",
      "PLC & Process Control Systems",
      "Security & Emergency Backup Systems",
      "Medical & Laboratory Equipment",
      "Banks & ATM Centres",
      "Critical Equipment Requiring Constant Voltage & Frequency"
    ]
  },
  {
    id: "kv-online-ups-system",
    slug: "online-ups-system",
    name: "Online UPS System",
    category: "UPS",
    parentCategory: "Power Products",
    description: "Rating: 5 KVA – 10 KVA. True Online Double Conversion UPS System with DSP control, IGBT switching, and ±1% voltage regulation.",
    specifications: {
      "Phase": "1 Phase Input – 1 Phase Output",
      "Capacity Range": "5 KVA – 10 KVA",
      "Technology": "DSP Based, IGBT Switching",
      "UPS Type": "True Online Double Conversion UPS",
      "Input Voltage": "230V ±20%, Single Phase",
      "Output Voltage": "230V AC, Single Phase",
      "Voltage Regulation": "±1%",
      "Input Frequency": "50Hz ±6%",
      "Output Frequency": "50Hz ±0.1Hz",
      "DC Voltage": "144V / 180V / 192V DC",
      "Charging Time": "12 Hours for 90% Full Capacity",
      "Charging Type": "CVCC (Constant Current Constant Voltage)",
      "Waveform": "Pure PWM Sine Wave",
      "Harmonic Distortion": "Less than 3% (Linear Load)",
      "Efficiency": "Up to 90%",
      "Power Factor": "0.8",
      "Overload Capacity": "110% for 5 Minutes",
      "Crest Factor": "3:1",
      "Audible Noise": "Less than 55 dB @ 1 Meter",
      "Operating Temperature": "0°C to 40°C",
      "Humidity": "Maximum 95%, Non-Condensing"
    },
    image: "/products/online-ups.png",
    downloadUrl: "#",
    features: [
      "True Online Double Conversion",
      "DSP Control with IGBT Switching",
      "Pure PWM Sine Wave Waveform",
      "±1% Output Voltage Regulation",
      "Audible Noise Less than 55 dB"
    ],
    applications: [
      "Data Centers & Servers",
      "Medical Diagnostic Equipment",
      "Telecommunication Networks",
      "Industrial Control Rooms"
    ]
  },
  {
    id: "kv-single-phase-servo-controlled-voltage-stabilizer",
    slug: "single-phase-servo-controlled-voltage-stabilizer",
    name: "Single Phase Servo Controlled Voltage Stabilizer",
    category: "Stabilizer",
    parentCategory: "Power Products",
    description: "Capacity: 1 KVA – 30 KVA. Single Phase Stabilizer with ±1% Output Accuracy, continuous duty cycle, and stud mounting.",
    specifications: {
      "Phase": "Single Phase",
      "Capacity Range": "1 KVA – 30 KVA",
      "Input Voltage": "As per customer requirement (Example: 170V – 270V)",
      "Output Voltage": "220V / 230V",
      "Output Voltage Accuracy": "±1%",
      "Cooling Method": "Natural Air Cooled",
      "Duty Cycle": "Continuous",
      "Frequency": "47–53 Hz",
      "Waveform Distortion": "NIL",
      "Efficiency": "Better than 97%",
      "Environment": "Indoor Application",
      "Mounting": "Stud Mounted",
      "Metering": "Analog Voltmeter",
      "Output Adjustment": "Potentiometer for Output Voltage Adjustment"
    },
    image: "/products/servo-stabilizer.png",
    downloadUrl: "#",
    features: [
      "±1% Output Voltage Accuracy",
      "Continuous Duty Cycle",
      "Analog Voltmeter Metering",
      "Potentiometer for Output Voltage Adjustment",
      "Natural Air Cooled"
    ],
    applications: [
      "Indoor Application",
      "Home & Office Appliances",
      "Sensitive Electronic Equipment"
    ]
  },
  {
    id: "kv-three-phase-servo-controlled-voltage-stabilizer",
    slug: "three-phase-servo-controlled-voltage-stabilizer",
    name: "Three Phase Servo Controlled Voltage Stabilizer",
    category: "Stabilizer",
    parentCategory: "Power Products",
    description: "Capacity: 3 KVA – 1000 KVA. Heavy-duty Three Phase Stabilizer with microprocessor-based LCD controller, ±1% output accuracy, and metallic enclosure on wheels.",
    specifications: {
      "Phase": "Three Phase",
      "Capacity Range": "3 KVA – 1000 KVA",
      "Cooling Type": "Air Cooled / Oil Cooled",
      "Controller": "Microprocessor Based LCD Display Module",
      "Operation": "Manual / Automatic",
      "Input Voltage": "360–460V, 360–480V, 340–480V, 310–480V, 350–500V (As per requirement)",
      "Output Voltage": "380V / 400V / 415V",
      "Output Voltage Accuracy": "±1%",
      "Cooling Method": "Natural Air Cooled & Oil Cooled",
      "Duty Cycle": "Continuous",
      "Frequency": "47–53 Hz",
      "Waveform Distortion": "NIL",
      "Efficiency": "Better than 98%",
      "Rate of Correction": "40–60 V/S",
      "Response Time": "Less Than 10 ms",
      "Environment": "Indoor Application",
      "Mounting": "Free on Wheels",
      "Enclosure": "RAL 7032/7035 Powder Coated Metallic Enclosure with Wheels"
    },
    image: "/products/three-phase-stabilizer.png",
    downloadUrl: "#",
    features: [
      "Microprocessor Based LCD Display Module",
      "Better than 98% Efficiency",
      "40–60 V/S Rate of Correction",
      "RAL 7032/7035 Metallic Enclosure with Wheels"
    ],
    applications: [
      "Industrial Plants",
      "Commercial Buildings",
      "Data Centers & Telecommunications"
    ]
  },
  {
    id: "kv-kps-st01",
    slug: "kps-st01-servo-stabilizer",
    name: "KARVIN Servo Voltage Stabilizer",
    category: "Servo Stabilizers",
    parentCategory: "Power Products",
    description: "Capacity: 10kVA - 500kVA. Highly durable stabilizer engineered for industrial loads.",
    specifications: {
      "Wattage Range": "10kVA - 500kVA",
      "Input Voltage": "300V - 460V AC",
      "IP Rating": "IP42 / IP54",
      "Luminous Efficacy": "High Efficiency Power Conversion",
    },
    image: "https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&q=80&w=800",
    downloadUrl: "#",
    features: ["Digital Microcontroller based control", "Overload & Short Circuit Protection"],
    applications: ["Industrial Plants", "CNC Machines", "Hospitality Units"]
  },
  {
    id: "kv-kps-tr01",
    slug: "kps-tr01-isolation-transformer",
    name: "KARVIN Ultra Isolation Transformer",
    category: "Isolation Transformers",
    parentCategory: "Power Products",
    description: "Capacity: 5kVA - 200kVA. Reduces electrical noise and voltage spikes for sensitive equipment.",
    specifications: {
      "Wattage Range": "5kVA - 200kVA",
      "Input Voltage": "415V AC",
      "IP Rating": "IP31",
      "Luminous Efficacy": "High Noise Attenuation",
    },
    image: "https://images.unsplash.com/photo-1498084393753-b411b2d26b34?auto=format&fit=crop&q=80&w=800",
    downloadUrl: "#",
    features: ["High noise attenuation of 120 dB", "Excellent regulation and low losses"],
    applications: ["Hospitals & Medical Labs", "Data Centers", "Telecom Setup"]
  }
];
